name: Java CI

on: [push]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # run linter
      - name: Run Checkstyle Linter
        run: make check

      # build everything (includes running unit tests)
      - name: Run JUnit Tests
        run: make test

      # report the results
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # always run even if the previous step fails
        with:
          name: 'JUnit Test Report'
          path: 'reports/TEST-*.xml'
          reporter: java-junit
          only-summary: false
