name: 'JUnit Test Report'
on:
  workflow_run:
    workflows: ['Java CI']                # runs after CI workflow
    types:
      - completed
jobs:
  report:
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: JUnit Tests                 # name of the check run which will be created
        path: '*.xml'                     # path to test results (inside artifact .zip)
        reporter: java-junit
        only-summary: false
